### PR TITLE
Add new RPG: Ker Nethalas

### PR DESCRIPTION
**Pull request by Eleksar387**
Adds a new RPG named "Ker Nethalas - Into the Midnight Throne"

### CODE REVIEW

**Comment by isaaclyman** [comment]
Thanks for the PR, but it appears this game doesn't meet the [criteria for inclusion](https://github.com/isaaclyman/ttrpg-guide?tab=readme-ov-file#criteria). The Blackoath Entertainment Discord is presumably for all their games, not just Ker Nathalas.

**Comment by Eleksar387** [comment]
Well true but there is a dedicated channel for the game in the discord. Admittedly there is also no separet reddit sub but you find a lot of mentions in https://www.reddit.com/r/Solo_Roleplaying and also quite a few reviews and playthroughs on YouTube.

**Comment by Eleksar387** [comment]
I get this. But just basing it on discord servers might be a bit hard. Some games have big forums or communities on Facebook and  I am not aware of discord servers.

**Comment by isaaclyman** [comment]
Forums or Facebook pages with a publicly visible headcount are definitely acceptable as proof of popularity. I'd have to modify the JSON structure a bit to fit them in, but don't hesitate to submit if they're game-specific and over 1,000 members.

**Comment by isaaclyman** [comment]
Or rather, "system-specific." If all of Blackoath's games run on the same core system, it could be added with the games as properties.

**Pull request closed without merging**
